#!/bin/bash

#echo "22" > /sys/class/gpio/unexport          # Пин подключения кнопки (менять, если другой)    
#echo "22" > /sys/class/gpio/export
#echo "in" > /sys/class/gpio/gpio22/direction

last_value=1

sleep_time=0.1

while true
do
    cur_value=$(cat ~/test_button) # cat /sys/class/gpio/gpio22/value

    if [ $cur_value -eq 0 ]
    then
        sleep $sleep_time

        if [[ $cur_value -eq 0 ]] && [[ $last_value -ne $cur_value ]]
        then
            last_value=$cur_value
            cur_date=$(date +"%T.%N")
            echo "$cur_date - $cur_value" # >> button_data
        fi

    else
        last_value=$cur_value

    fi

    sleep $sleep_time
done
