#!/bin/bash

sudo echo "22" >> /sys/class/gpio/unexport          # Пин подключения кнопки (менять, если другой)    
sudo echo "22" >> /sys/class/gpio/export
sudo echo "in" > /sys/class/gpio/gpio22/direction

sudo echo "23" >> /sys/class/gpio/unexport          # Пин подключения кнопки (менять, если другой)
sudo echo "23" >> /sys/class/gpio/export
sudo echo "in" > /sys/class/gpio/gpio23/direction

read what_btn

sleep_time=0.05

if [[ $what_btn -eq "1b" ]]
then

    while :
    do

        cur_value_0=$(cat /sys/class/gpio/gpio22/value)
        cur_value_1=$(cat /sys/class/gpio/gpio23/value)

        if [[ $cur_value_0 -eq 0 ]] || [[ $cur_value_1 -eq 0 ]]
        then
            sleep $sleep_time

            cur_value_0=$(cat /sys/class/gpio/gpio22/value)
            cur_value_1=$(cat /sys/class/gpio/gpio23/value)

            if [[ $cur_value_0 -eq "0" ]]
            then
                text="Button 0"
                echo $text > button_data
                break
            elif [[ $cur_value_1 -eq "0" ]]
            then
                text="Button 1"
                echo $text > button_data
                break
            fi

        else
            continue
        fi

    done

elif [[ $what_btn -eq "0b" ]]
then

    cur_value_0=$(cat /sys/class/gpio/gpio22/value)

    if [[ $cur_value_0 -eq 0 ]]
    then
        sleep $sleep_time

        cur_value_0=$(cat /sys/class/gpio/gpio22/value)

        if [[ $cur_value_0 -eq "0" ]]
        then
            text="Button 0"
            echo $text > button_data
        else
            echo "Nothing" > button_data
        fi

    fi

fi